---
# Set up apache vhosts
- name: Copy virtual host setup over
  template: src=vhost.conf dest=/etc/apache2/sites-available/

# Set username and group for apache to be the vagrant user's
- name: Copy Apache envars
  template: src=envvars dest=/etc/apache2/

- name: Activate virtual host
  command: a2ensite vhost
  notify: Restart webserver

- name: disable default virtual host
  command: a2dissite 000-default
  notify: Restart apache

# Set up database and seed with docs/{{ mysql_dbname }}.sql (via a handler)
- name: Setup MySQL user
  mysql_user: name={{ mysql_username }} password={{ mysql_password }} host={{ item }} priv={{ mysql_dbname }}.*:ALL state=present
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost

- name: Give permissions to {{ mysql_username }} for phpmyadmin configuration tables
  mysql_user: >
    name={{ mysql_username }} password={{ mysql_password }} host={{ item }}
    append_privs=yes priv=phpmyadmin.*:ALL state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create {{ mysql_dbname }} database
  mysql_db: name={{ mysql_dbname }} encoding=utf8 collation=utf8_unicode_ci state=present login_user=root login_password={{ mysql_root_password }}
  notify: Import database

- name: Setup MySQL creds for {{ mysql_username}}
  template: src=local.my.cnf dest=/home/vagrant/.my.cnf owner=vagrant mode=0600
